# Generated by Django 3.0.3 on 2020-04-04 05:27

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaSekolah', models.CharField(default='', max_length=60, verbose_name='Nama Sekolah')),
                ('npsn', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='NPSN')),
                ('bp', models.CharField(blank=True, choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA'), ('SMK', 'SMK')], max_length=10, null=True, verbose_name='BP')),
                ('status', models.CharField(blank=True, choices=[('NEGERI', 'NEGERI'), ('SWASTA', 'SWASTA')], max_length=7, null=True, verbose_name='STATUS')),
                ('lastSync', models.DateTimeField(default=django.utils.timezone.now)),
                ('jumlahSync', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Jumlah Sync')),
                ('pd', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='Jumlah Peserta Didik')),
                ('rombel', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Jumlah Rombongan Belajar')),
                ('guru', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Jumlah Guru')),
                ('pegawai', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Jumlah Pegawai')),
                ('rKelas', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Jumlah Ruang Kelas')),
                ('rLab', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Jumlah Ruang Lab.')),
                ('rPerpus', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Jumlah Ruang Perpustakaan')),
            ],
        ),
    ]
