# Generated by Django 3.0.3 on 2020-05-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_post_pilihkecamatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pilihKecamatan',
            field=models.CharField(blank=True, choices=[('Ampelgading', 'Ampelgading'), ('Bantur', 'Bantur'), ('Bululawang', 'Bululawang'), ('Dampit', 'Dampit'), ('Dau', 'Dau'), ('Donomulyo', 'Donomulyo'), ('Gedangan', 'Gedangan'), ('Gondanglegi', 'Gondanglegi'), ('Jabung', 'Jabung'), ('Kalipare', 'Kalipare'), ('Karangploso', 'Karangploso'), ('Kasembon', 'Kasembon'), ('Kepanjen', 'Kepanjen'), ('Kromengan', 'Kromengan'), ('Lawang', 'Lawang'), ('Ngajum', 'Ngajum'), ('Ngantang', 'Ngantang'), ('Pagak', 'Pagak'), ('Pagelaran', 'Pagelaran'), ('Pakis', 'Pakis'), ('Pakisaji', 'Pakisaji'), ('Poncokusumo', 'Poncokusumo'), ('Pujon', 'Pujon'), ('Sumbermanjing Wetan', 'Sumbermanjing Wetan'), ('Singosari', 'Singosari'), ('Sumberpucung', 'Sumberpucung'), ('Tajinan', 'Tajinan'), ('Tirtoyudo', 'Tirtoyudo'), ('Tumpang', 'Tumpang'), ('Turen', 'Turen'), ('Wagir', 'Wagir'), ('Wajak', 'Wajak'), ('Wonosari', 'Wonosari')], max_length=100, null=True, verbose_name='Pilih Kecamatan'),
        ),
    ]
