# Generated by Django 3.0.3 on 2020-06-14 03:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200504_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rasioGRB',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Rasio Guru / Rombel'),
        ),
        migrations.AddField(
            model_name='post',
            name='rasioPDRB',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Rasio Peserta Didik / Rombel'),
        ),
    ]
